apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: wordpress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`hojat.local.com`) 
      kind: Rule
        - name: {{ template "common.names.fullname" . }}
          port: 80
    - match: Host(`hojat.local.com`) && Path(`/wordpress`)
      kind: Rule
      middlewares:
        - name: strip-wordpress
      services:
        - name: {{ template "common.names.fullname" . }}
          port: 80
    - match: Host(`hojat.local.com`) && Path(`/dbadmin`)
      kind: Rule
      middlewares:
        - name: strip-dbadmin
      services:
        - name: phpmyadmin
          port: 80

